library(data.table)
rt <- fread('household_power_consumption.txt', na.strings = '?')
rt$Date <- as.Date(rt$Date, "%d/%m/%Y")
nrt <- subset(rt, Date == "2007-02-01" | Date == "2007-02-02")
rm(rt)
ref_time <- paste(nrt$Date, nrt$Time, sep = " ")
ref_time <- strptime(ref_time, "%Y-%m-%d %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(ref_time, nrt$Global_active_power, type='l', xlab="",ylab="Globle Active Power (killowatts)")
dev.off()
