library(data.table)
rt <- fread('household_power_consumption.txt', na.strings = '?')
rt$Date <- as.Date(rt$Date, "%d/%m/%Y")
nrt <- subset(rt, Date == "2007-02-01" | Date == "2007-02-02")
rm(rt)
ref_time <- paste(nrt$Date, nrt$Time, sep = " ")
ref_time <- strptime(ref_time, "%Y-%m-%d %H:%M:%S")
png("plot4.png", width = 480, height = 480)
opar <- par()
par(mfcol=c(2,2), mar=c(5,4,2,1))
plot(ref_time, nrt$Global_active_power, type='l', xlab="", ylab="Globle Active Power")
plot(ref_time, nrt$Sub_metering_1, type='l', xlab="", ylab="Energy sub metering")
lines(ref_time,nrt$Sub_metering_2, col='red')
lines(ref_time,nrt$Sub_metering_3, col='blue')
legend("topright", lty=c(1,1,1), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"))
with(nrt, plot(ref_time, Voltage, type='l', xlab="datetime"))
with(nrt, plot(ref_time, Global_reactive_power, type='l', xlab="datetime"))
dev.off()
par(opar)
